from typing import TypedDict, Tuple, Union

from werkzeug.datastructures import FileStorage


class PdfFileData(TypedDict):
    """Dict generated by InitPdfRenderingSchema."""

    pdf_file: FileStorage


ConvertSize = Union[Tuple[int, None], Tuple[None, int]]
