"""Initial migration

Revision ID: d1f08344b620
Revises: 
Create Date: 2022-05-15 13:47:43.879273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d1f08344b620"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rendering_pdf_event",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEW", "PROCESSING", "FAILED", "DONE", name="processingstatus"),
            nullable=True,
        ),
        sa.Column("total_page_count", sa.Integer(), nullable=True),
        sa.Column("processed_page_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rendering_pdf_event")
    # ### end Alembic commands ###
